openapi: '3.0.2'
info:
  title: Staff Management System
  description: A staff management system for effectively managing staff, their offices, and 
                allocated courses within the Faculty of Computing and Informatics. 
  version: '1.0'
servers:
  - url: http://localhost:8000
paths: 
  /addLecturer:
    summary: A point for adding a lecturer
    post:
      requestBody:
        content:
          application/json:
            schema: 
              description: A Lecturer object with with staffNumber, officeNumber,name, title and coursesTaught
              $ref: "#/components/schemas/Lecturer"
      responses:
        '200':
          description: A string with a message showing success
          content:
            application/json:
              schema:
                type: string
        '404':
          description: An error 


components:
  schemas:
    Course:
      type: object
      properties:
        name:
          type: string
        code:
          type: string
        lecturers:
          type: array
          items:
            type: string
  responses:
    ErrorResponse:
      description: The specified resource was not found.
    Error500Response:
      description: Internal Server Crushed
    Error404Response:
      description: Course not Found
    Error403Response:
      description: Access Denied
